Add new parameters to push methods
ChartIQ/ChartIQ-iOS-SDK pull request #38
Opened 2022-08-12 17:43 UTC by jdrichards50

2022-08-19 17:21 UTC, mwilber-ciq commented on Source/ChartIQScriptManager.swift
>    ///   - jsonString: The String Object.
Update parameter description

2022-08-19 17:21 UTC, mwilber-ciq commented on Source/ChartIQScriptManager.swift
>    ///   - cb: The String Object.
Update parameter description

2022-08-19 17:21 UTC, mwilber-ciq commented on Source/ChartIQView.swift
>    ///   - data: An array of properly formatted OHLC quote objects to create a chart.
Same for these docs

2022-08-19 18:34 UTC, jdrichards50 commented on Source/ChartIQScriptManager.swift
>    ///   - jsonString: The String Object.
whoops, totally forgot about these.

2022-08-22 18:25 UTC, mwilber-ciq commented on Source/ChartIQScriptManager.swift
> +  ///   - data: data: The data you want to display on the chart as a JSON string.
Remove the extra `data:`

2022-08-22 18:27 UTC, mwilber-ciq requested changes
Just the one edit below. GitHub doesn't seem to do suggested changes with swift.

2022-08-22 19:41 UTC, mwilber-ciq approved these changes

2022-09-02 19:04 UTC, merged